// Ninja Bear Studio Inc., all rights reserved.
#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

NINJAGASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_GASP_Ability_Jog);
NINJAGASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_GASP_Ability_Sprint);
NINJAGASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_GASP_Ability_Walk);
NINJAGASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_GASP_Component_Mesh_Primary);
NINJAGASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_GASP_Component_Mesh_Retarget);
NINJAGASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_GASP_Component_Mesh_Overlay_Skeletal);
NINJAGASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_GASP_Component_Mesh_Overlay_Static);
